
texto = 'WRZWAFPAGJIPHVKWCIDVKWCARVGYVGAWFPVEEWEWFPIDPHWEJFKVCAFMVCAPAVWRXHVOWEVHRAKWFQHVGSHWMHWEVXHWGAXAPIKICWFPWIEJGIEAPIEAPJIKIWFWRFJCWHVKAWGAFJWZWKWRISVFAMEPHIEEWJFIKWRIEGIRRWECIEIFPAMJIEKWRQIHHAVZAWTVKWYICQJHMVRIQJWFIKWCIHPIKWQAVKWGHWWHNJWAQICJDHWPHIEIKIXJWERIGVCAKIIXWFIEWCXWBIQIIGVGWHWFWRYVHFARRVKWRIGVGAFIQJWFVCWKATWIICACAECVEACAPAVNJWWEWRCIEACXIGAWFPWKWPVKVERVEYVCQHWEZAWFWGVFYICQHWIHCIHIJFWEGIFKIRVKWRVEKWCVFAVEDIWEPIINJAWREWFVHRAKWFQHVGSWLGRICVRIXVQHWCIHPIIEJEPIKIWFPHWIQHAWFKVRIXJWHPIKWRGVCWKVHEACIHPIXWHVFVACXVHPINJWRIGVCAKIFVWEPWRAEPIXVHNJWPVKIZAIFVEVFRIEKVEIGIQIKWKIHRICWKAIWFEIAFPCAGYWRWFPVFGWEXVHNJWYIZJWRPVWREWFVHRAKWFQHVGSWEVWERVNJWWRFVEKAHIINJAZAWFWDVCWWEGIXVEWFVHILWRYIMICWJEPWKWROIZVHKWGIRCIHRWDRIWLGWRWFPWEAHZAWFPIHWMHWEVXHWEJHVEIIEJRIQVHIPVHAVGJRAFIHAVCWNJWKWEVRVDGVCVCAGIHIGPWHJFPIFPVPACAKVFVCJXWHCAPAIYIGWHOHWFPWIRCIEAHIEGAQRWKWRVEXHVOWEVHWECWAEXVFAIIHWPAHIHCWICAXWNJWFIYIQAPIGAVFKWRXAEVIRPVGJIFKVRIXJWHPIKWRIGIRRWGHJTAVEVQHWEJEMVBFWERVEMHIFKWEXAWEKWCAPAVYAGAWHVFHWGYAFIHRIWEGIRWHIKWCIKWHIDWRKJWFVKWRIGIEIIPHIZWEVWRGVCWKVHDEWXHWGAXAPVWFEJKWEXIGYVWFEJHIXAKICIHGYIEVRVPJZVPAWCXVKWIHHVTIHWRQIEPVFIJFHAFGVFWREVCQHWHVKWMHIFKWEIRIEIRICWEIDKWGAHCWWFPVFVACXWHAVEVILWREAMJWCWPVKIZAIFVYIQAIPWFAKVPAWCXVKWCVZWHCWGJIFKVWRXHVOWEVHCWMHAPVWFPVFVKWZAZVWFVTVDQAWFPVKIZAIFVWEPIEINJACWXHWGAXAPWWFWRKWEXIGYVKWCAAHIEGAQRWCIWEPHV'

resultado= ''
for letra in texto:
    if letra == "W":
        resultado += "E"
    elif letra == "I":
        resultado += "A"
    elif letra == "V":
        resultado += "O"
    elif letra == "F":
        resultado += "N"
    elif letra == "P":
        resultado += "T"
    elif letra == "G":
        resultado += "C"
    elif letra == "E":
        resultado += "S"
    elif letra == "Y":
        resultado += "H"
    elif letra == "A":
        resultado += "I"
    elif letra == "D":
        resultado += "Y"
    elif letra == "H":
        resultado += "R"
    elif letra == "R": 
        resultado += "L"
    elif letra == "Z":
        resultado += "V"
    elif letra == "J":
        resultado += "U"
    elif letra == "K":
        resultado += "D"
    elif letra == "C":
        resultado += "M"
    elif letra == "M":
        resultado += "G"
    elif letra == "Q":
        resultado += "B"
    elif letra == "X":
        resultado += "P"
    elif letra == "O":
        resultado += "F"
    elif letra =="T":
        resultado += "J"
    elif letra == "S":
        resultado += "K"
    elif letra == "N" :
        resultado += "Q"
    elif letra == "B":
        resultado += "Z"
    elif letra == "L":
        resultado += "X"





    else:
        resultado += "_"     
    
print(resultado)